# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doreenselly', '0002_auto_20160428_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payable',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
