# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doreenselly', '0003_auto_20160406_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='docfile',
            field=models.FileField(blank=True, upload_to='doreenselly/static/images/document/%Y%m%d'),
        ),
    ]
