# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doreenselly', '0003_auto_20160428_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
