# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doreenselly', '0004_auto_20160428_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payable',
            field=models.PositiveIntegerField(),
        ),
    ]
