# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doreenselly', '0008_auto_20160429_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='country',
            field=models.CharField(choices=[('SELECT', ''), ('USA', 'USA'), ('KENYA', 'KENYA')], max_length=32, null=True),
        ),
    ]
